-- Sesión 50 — Jefes: defs, instancia, botín (pieza de dragón 1/20) y estado. Generado desde client/src/shared/bosses.js
INSERT OR REPLACE INTO npc_defs (id,name,max_hp,attack_lvl,strength_lvl,defence_lvl,attack_speed_ticks,max_hit,xp_per_kill,respawn_ms,spawn_x,spawn_z,attack_range,model,behavior,aggro_radius,style) VALUES ('rey_yeti','Rey Yeti Grom',260,62,60,45,5,20,0,120000,480,-1900,3.2,'rey_yeti','boss',0,'melee');
DELETE FROM npc_loot_table WHERE npc_def_id='rey_yeti';
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('rey_yeti','bones',3,3,1,1);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('rey_yeti','shark',2,2,1,1);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('rey_yeti','helm_dragon',1,1,1,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('rey_yeti','coins',3000,8000,6,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('rey_yeti','bar_teiderio',2,4,4,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('rey_yeti','arrow_teiderio',30,60,4,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('rey_yeti','yew_logs',5,8,3,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('rey_yeti','raw_shark',5,10,2,0);
DELETE FROM npc_instances WHERE def_id='rey_yeti';
INSERT INTO npc_instances (def_id,hp_current,x,z,status,spawn_x,spawn_z) VALUES ('rey_yeti',260,480,-1900,0,480,-1900);
INSERT OR IGNORE INTO boss_state (boss_id,last_tick,hazards) VALUES ('rey_yeti',0,'[]');
INSERT OR REPLACE INTO npc_defs (id,name,max_hp,attack_lvl,strength_lvl,defence_lvl,attack_speed_ticks,max_hit,xp_per_kill,respawn_ms,spawn_x,spawn_z,attack_range,model,behavior,aggro_radius,style) VALUES ('coloso_obsidiana','Coloso de Obsidiana',320,60,62,70,6,22,0,120000,1330,-1560,3.4,'coloso_obsidiana','boss',0,'melee');
DELETE FROM npc_loot_table WHERE npc_def_id='coloso_obsidiana';
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('coloso_obsidiana','bones',3,3,1,1);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('coloso_obsidiana','shark',2,2,1,1);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('coloso_obsidiana','legs_dragon',1,1,1,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('coloso_obsidiana','coins',3000,8000,6,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('coloso_obsidiana','bar_teiderio',2,4,4,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('coloso_obsidiana','arrow_teiderio',30,60,4,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('coloso_obsidiana','yew_logs',5,8,3,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('coloso_obsidiana','raw_shark',5,10,2,0);
DELETE FROM npc_instances WHERE def_id='coloso_obsidiana';
INSERT INTO npc_instances (def_id,hp_current,x,z,status,spawn_x,spawn_z) VALUES ('coloso_obsidiana',320,1330,-1560,0,1330,-1560);
INSERT OR IGNORE INTO boss_state (boss_id,last_tick,hazards) VALUES ('coloso_obsidiana',0,'[]');
INSERT OR REPLACE INTO npc_defs (id,name,max_hp,attack_lvl,strength_lvl,defence_lvl,attack_speed_ticks,max_hit,xp_per_kill,respawn_ms,spawn_x,spawn_z,attack_range,model,behavior,aggro_radius,style) VALUES ('reina_escorpion','Reina Sekhet',280,64,58,50,4,19,0,120000,1480,400,4,'reina_escorpion','boss',0,'ranged');
DELETE FROM npc_loot_table WHERE npc_def_id='reina_escorpion';
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('reina_escorpion','bones',3,3,1,1);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('reina_escorpion','shark',2,2,1,1);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('reina_escorpion','boots_dragon',1,1,1,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('reina_escorpion','coins',3000,8000,6,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('reina_escorpion','bar_teiderio',2,4,4,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('reina_escorpion','arrow_teiderio',30,60,4,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('reina_escorpion','yew_logs',5,8,3,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('reina_escorpion','raw_shark',5,10,2,0);
DELETE FROM npc_instances WHERE def_id='reina_escorpion';
INSERT INTO npc_instances (def_id,hp_current,x,z,status,spawn_x,spawn_z) VALUES ('reina_escorpion',280,1480,400,0,1480,400);
INSERT OR IGNORE INTO boss_state (boss_id,last_tick,hazards) VALUES ('reina_escorpion',0,'[]');
INSERT OR REPLACE INTO npc_defs (id,name,max_hp,attack_lvl,strength_lvl,defence_lvl,attack_speed_ticks,max_hit,xp_per_kill,respawn_ms,spawn_x,spawn_z,attack_range,model,behavior,aggro_radius,style) VALUES ('bruja_pantano','Morgath',240,66,60,48,5,18,0,120000,-640,760,4,'bruja_pantano','boss',0,'magic');
DELETE FROM npc_loot_table WHERE npc_def_id='bruja_pantano';
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('bruja_pantano','bones',3,3,1,1);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('bruja_pantano','shark',2,2,1,1);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('bruja_pantano','gloves_dragon',1,1,1,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('bruja_pantano','coins',3000,8000,6,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('bruja_pantano','bar_teiderio',2,4,4,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('bruja_pantano','arrow_teiderio',30,60,4,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('bruja_pantano','yew_logs',5,8,3,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('bruja_pantano','raw_shark',5,10,2,0);
DELETE FROM npc_instances WHERE def_id='bruja_pantano';
INSERT INTO npc_instances (def_id,hp_current,x,z,status,spawn_x,spawn_z) VALUES ('bruja_pantano',240,-640,760,0,-640,760);
INSERT OR IGNORE INTO boss_state (boss_id,last_tick,hazards) VALUES ('bruja_pantano',0,'[]');
INSERT OR REPLACE INTO npc_defs (id,name,max_hp,attack_lvl,strength_lvl,defence_lvl,attack_speed_ticks,max_hit,xp_per_kill,respawn_ms,spawn_x,spawn_z,attack_range,model,behavior,aggro_radius,style) VALUES ('leviatan','Leviatán',300,66,60,52,5,18,0,120000,-450,1950,4,'leviatan','boss',0,'magic');
DELETE FROM npc_loot_table WHERE npc_def_id='leviatan';
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('leviatan','bones',3,3,1,1);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('leviatan','shark',2,2,1,1);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('leviatan','shield_dragon',1,1,1,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('leviatan','coins',3000,8000,6,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('leviatan','bar_teiderio',2,4,4,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('leviatan','arrow_teiderio',30,60,4,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('leviatan','yew_logs',5,8,3,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('leviatan','raw_shark',5,10,2,0);
DELETE FROM npc_instances WHERE def_id='leviatan';
INSERT INTO npc_instances (def_id,hp_current,x,z,status,spawn_x,spawn_z) VALUES ('leviatan',300,-450,1950,0,-450,1950);
INSERT OR IGNORE INTO boss_state (boss_id,last_tick,hazards) VALUES ('leviatan',0,'[]');
INSERT OR REPLACE INTO npc_defs (id,name,max_hp,attack_lvl,strength_lvl,defence_lvl,attack_speed_ticks,max_hit,xp_per_kill,respawn_ms,spawn_x,spawn_z,attack_range,model,behavior,aggro_radius,style) VALUES ('rey_esqueleto','Varkhul',320,68,64,58,4,20,0,120000,-1500,-440,3.2,'rey_esqueleto','boss',0,'melee');
DELETE FROM npc_loot_table WHERE npc_def_id='rey_esqueleto';
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('rey_esqueleto','bones',3,3,1,1);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('rey_esqueleto','shark',2,2,1,1);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('rey_esqueleto','staff_dragomante',1,1,1,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('rey_esqueleto','coins',3000,8000,6,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('rey_esqueleto','bar_teiderio',2,4,4,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('rey_esqueleto','arrow_teiderio',30,60,4,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('rey_esqueleto','yew_logs',5,8,3,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('rey_esqueleto','raw_shark',5,10,2,0);
DELETE FROM npc_instances WHERE def_id='rey_esqueleto';
INSERT INTO npc_instances (def_id,hp_current,x,z,status,spawn_x,spawn_z) VALUES ('rey_esqueleto',320,-1500,-440,0,-1500,-440);
INSERT OR IGNORE INTO boss_state (boss_id,last_tick,hazards) VALUES ('rey_esqueleto',0,'[]');
INSERT OR REPLACE INTO npc_defs (id,name,max_hp,attack_lvl,strength_lvl,defence_lvl,attack_speed_ticks,max_hit,xp_per_kill,respawn_ms,spawn_x,spawn_z,attack_range,model,behavior,aggro_radius,style) VALUES ('dragon_rojo','Vermithrax',400,70,68,60,5,24,0,120000,-1850,40,3.8,'dragon_rojo','boss',0,'melee');
DELETE FROM npc_loot_table WHERE npc_def_id='dragon_rojo';
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('dragon_rojo','bones',3,3,1,1);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('dragon_rojo','shark',2,2,1,1);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('dragon_rojo','body_dragon',1,1,1,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('dragon_rojo','coins',3000,8000,6,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('dragon_rojo','bar_teiderio',2,4,4,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('dragon_rojo','arrow_teiderio',30,60,4,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('dragon_rojo','yew_logs',5,8,3,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('dragon_rojo','raw_shark',5,10,2,0);
DELETE FROM npc_instances WHERE def_id='dragon_rojo';
INSERT INTO npc_instances (def_id,hp_current,x,z,status,spawn_x,spawn_z) VALUES ('dragon_rojo',400,-1850,40,0,-1850,40);
INSERT OR IGNORE INTO boss_state (boss_id,last_tick,hazards) VALUES ('dragon_rojo',0,'[]');
INSERT OR REPLACE INTO npc_defs (id,name,max_hp,attack_lvl,strength_lvl,defence_lvl,attack_speed_ticks,max_hit,xp_per_kill,respawn_ms,spawn_x,spawn_z,attack_range,model,behavior,aggro_radius,style) VALUES ('dragon_negro','Nidhogg',500,76,72,66,5,26,0,180000,-1600,-1540,4,'dragon_negro','boss',0,'melee');
DELETE FROM npc_loot_table WHERE npc_def_id='dragon_negro';
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('dragon_negro','bones',3,3,1,1);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('dragon_negro','shark',2,2,1,1);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('dragon_negro','bow_dragon',1,1,1,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('dragon_negro','coins',3000,8000,6,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('dragon_negro','bar_teiderio',2,4,4,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('dragon_negro','arrow_teiderio',30,60,4,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('dragon_negro','yew_logs',5,8,3,0);
INSERT INTO npc_loot_table (npc_def_id,item_id,qty_min,qty_max,weight,is_always) VALUES ('dragon_negro','raw_shark',5,10,2,0);
DELETE FROM npc_instances WHERE def_id='dragon_negro';
INSERT INTO npc_instances (def_id,hp_current,x,z,status,spawn_x,spawn_z) VALUES ('dragon_negro',500,-1600,-1540,0,-1600,-1540);
INSERT OR IGNORE INTO boss_state (boss_id,last_tick,hazards) VALUES ('dragon_negro',0,'[]');
