-- Sesión 50 — Herbología: hierbas canarias, vial, gofio y pociones (3/2/1 dosis). Tienda La ASO.
INSERT OR REPLACE INTO items (id,name,icon,stackable,equip_slot,weapon_type,attack_bonus,defence_bonus,ranged_bonus,material,tier,smith_level,bars_required,base_price,description,created_at) VALUES ('hierba_tabaiba','Tabaiba','🌿',1,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,15,'Tabaiba dulce de la costa. Da fuerza al brazo que golpea.',0),
('hierba_verode','Verode','🌿',1,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,25,'Verode de los riscos: el que lo toma pega más fuerte.',0),
('hierba_salvia','Salvia canaria','🌿',1,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,40,'Salvia canaria, la hierba de la resistencia.',0),
('hierba_oregano','Orégano de risco','🌿',1,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,60,'Orégano de risco: afina la vista.',0),
('hierba_retama','Retama del Teide','🌿',1,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,80,'Flor de retama del Teide. Calma el espíritu.',0),
('hierba_tajinaste','Tajinaste rojo','🌿',1,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,110,'Flor del tajinaste rojo, solo crece en Las Cañadas. Huele a magia.',0),
('vial_agua','Vial de agua','🧪',1,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,5,'Un vial con agua de manantial. Base de toda poción.',0),
('gofio','Gofio','🌾',1,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,30,'Harina de millo tostado. Con gofio, cualquier poción pega el doble.',0),
('pocion_ataque_3','Poción de ataque (3)','🧪',0,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,225,'Sube tu nivel de Ataque durante 5 minutos. 3 dosis.',0),
('pocion_ataque_2','Poción de ataque (2)','🧪',0,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,150,'Sube tu nivel de Ataque durante 5 minutos. 2 dosis.',0),
('pocion_ataque_1','Poción de ataque (1)','🧪',0,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,75,'Sube tu nivel de Ataque durante 5 minutos. 1 dosis.',0),
('pocion_fuerza_3','Poción de fuerza (3)','🧪',0,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,360,'Sube tu nivel de Fuerza durante 5 minutos. 3 dosis.',0),
('pocion_fuerza_2','Poción de fuerza (2)','🧪',0,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,240,'Sube tu nivel de Fuerza durante 5 minutos. 2 dosis.',0),
('pocion_fuerza_1','Poción de fuerza (1)','🧪',0,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,120,'Sube tu nivel de Fuerza durante 5 minutos. 1 dosis.',0),
('pocion_defensa_3','Poción de defensa (3)','🧪',0,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,495,'Sube tu nivel de Defensa durante 5 minutos. 3 dosis.',0),
('pocion_defensa_2','Poción de defensa (2)','🧪',0,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,330,'Sube tu nivel de Defensa durante 5 minutos. 2 dosis.',0),
('pocion_defensa_1','Poción de defensa (1)','🧪',0,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,165,'Sube tu nivel de Defensa durante 5 minutos. 1 dosis.',0),
('pocion_distancia_3','Poción de distancia (3)','🧪',0,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,630,'Sube tu nivel de Distancia durante 5 minutos. 3 dosis.',0),
('pocion_distancia_2','Poción de distancia (2)','🧪',0,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,420,'Sube tu nivel de Distancia durante 5 minutos. 2 dosis.',0),
('pocion_distancia_1','Poción de distancia (1)','🧪',0,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,210,'Sube tu nivel de Distancia durante 5 minutos. 1 dosis.',0),
('pocion_plegaria_3','Poción de plegaria (3)','🧪',0,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,765,'Recupera puntos de plegaria. 3 dosis.',0),
('pocion_plegaria_2','Poción de plegaria (2)','🧪',0,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,510,'Recupera puntos de plegaria. 2 dosis.',0),
('pocion_plegaria_1','Poción de plegaria (1)','🧪',0,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,255,'Recupera puntos de plegaria. 1 dosis.',0),
('pocion_magia_3','Poción de magia (3)','🧪',0,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,900,'Sube tu nivel de Magia durante 5 minutos. 3 dosis.',0),
('pocion_magia_2','Poción de magia (2)','🧪',0,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,600,'Sube tu nivel de Magia durante 5 minutos. 2 dosis.',0),
('pocion_magia_1','Poción de magia (1)','🧪',0,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,300,'Sube tu nivel de Magia durante 5 minutos. 1 dosis.',0),
('super_ataque_3','Súper ataque (3)','🧪',0,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,1125,'Sube tu nivel de Ataque durante 5 minutos. 3 dosis.',0),
('super_ataque_2','Súper ataque (2)','🧪',0,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,750,'Sube tu nivel de Ataque durante 5 minutos. 2 dosis.',0),
('super_ataque_1','Súper ataque (1)','🧪',0,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,375,'Sube tu nivel de Ataque durante 5 minutos. 1 dosis.',0),
('super_fuerza_3','Súper fuerza (3)','🧪',0,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,1260,'Sube tu nivel de Fuerza durante 5 minutos. 3 dosis.',0),
('super_fuerza_2','Súper fuerza (2)','🧪',0,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,840,'Sube tu nivel de Fuerza durante 5 minutos. 2 dosis.',0),
('super_fuerza_1','Súper fuerza (1)','🧪',0,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,420,'Sube tu nivel de Fuerza durante 5 minutos. 1 dosis.',0),
('super_defensa_3','Súper defensa (3)','🧪',0,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,1440,'Sube tu nivel de Defensa durante 5 minutos. 3 dosis.',0),
('super_defensa_2','Súper defensa (2)','🧪',0,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,960,'Sube tu nivel de Defensa durante 5 minutos. 2 dosis.',0),
('super_defensa_1','Súper defensa (1)','🧪',0,NULL,NULL,0,0,0,NULL,NULL,NULL,NULL,480,'Sube tu nivel de Defensa durante 5 minutos. 1 dosis.',0);
INSERT OR REPLACE INTO shop_stock (shop_id,item_id,current_qty,max_qty,sell_price,buy_price) VALUES ('aso','vial_agua',500,500,5,2),('aso','gofio',200,200,30,12),('aso','hierba_tabaiba',300,300,15,7),('aso','hierba_verode',300,300,25,12),('aso','hierba_salvia',300,300,40,20),('aso','hierba_oregano',300,300,60,30),('aso','hierba_retama',300,300,80,40),('aso','hierba_tajinaste',300,300,110,55);
